---
# if http/https not specified, defaults to https
# if you put http here, it will try verify=false, not to check certs
host: "https://bookstack.mydomain.org"
# You could optionally set the bookstack token_id and token_secret here instead of env
# If using env vars instead you can leave values empty or omit this section
credentials:
  # set here or as env variable, BOOKSTACK_TOKEN_ID
  # env var takes precedence over below
  token_id: ""
  # set here or as env variable, BOOKSTACK_TOKEN_SECRET
  # env var takes precedence over below
  token_secret: ""
# supported formats from bookstack below
# specify one or more
formats:
  - markdown
  - html
  - pdf
  - plaintext
  - zip
# optional how to handle additional content for pages
assets:
  # optional export of all the images used in a page(s).
  # omit this or set to false if not needed
  export_images: false
  # optional export of all the attachments used in a page(s).
  # omit this or set to false if not needed
  export_attachments: false
  # optional modify markdown files to replace image url links
  # with local exported image paths
  modify_markdown: false
  ## optional export of metadata about the page in a json file
  # this metadata contains general information about the page
  # like: last update, owner, revision count, etc.
  # omit this or set to false if not needed
  export_meta: false
# optional - can override default http_config
# if not required, you can omit/comment out section
# https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html
# default backoff_factor 2.5 means we wait 5, 10, 20, and then 40 seconds before our last retry
# - this should allow for per minute rate limits to be refreshed
http_config:
  # whether or not to verify ssl certificates if using https
  verify_ssl: false
  # set http timeout in seconds for requests
  timeout: 30
  # default backoff_factor 2.5 means we wait 5, 10, 20, and then 40 seconds before our last retry
  # - this should allow for per minute rate limits to be refreshed
  backoff_factor: 2.5
  # which status codes trigger retries
  retry_codes: [413, 429, 500, 502, 503, 504]
  # number of retries
  retry_count: 5
  # any additional headers to add to http requests
  additional_headers:
    test: "test"
    test2: "test2"
    User-Agent: "test-agent"
# directory to export to
# relative or full path
output_path: "bkps/"
## optional - if specified exporter can delete older archives
# valid values are:
# set to -1 if you want to delete all archives after each run
# - this is useful if you only want to upload to object storage
# set to 1+ if you want to retain a certain number of archives
# set to 0 or comment out section if you want no action done
keep_last: 5
## optional - if specified exporter will run in a loop
# it will run and then pause for {run_interval} seconds before running again
# specify in seconds, example: 86400 seconds = 24 hours or run once a day
# omit/commit out or set to 0 if you just want a single run and exit
run_interval: 0
## optional - if specified exporter will send notifications on failure
# supported notification services are:
# - apprise (https://github.com/caronc/apprise)
# omit/comment out section if not required
notifications:
  # optional - apprise notification config
  # if used, required: specify one or more service_urls or a config_path
  # - if both are specified, config_path takes precedence
  # if service_urls is used, service_urls can also be specified as env var: APPRISE_URLS
  # - env var takes precedence over service_urls below if both specified
  apprise:
    service_urls: []
      # - "json://localhost:8080/notify"
    config_path: ""
    plugin_paths: []
    storage_path: ""
    custom_title: ""
    custom_attachment_path: ""
    on_success: false
    on_failure: true